development:
  sessions:
    default:
      database: honeypot_development
      hosts:
        - localhost
test:
  sessions:
    default:
      database: honeypot_test
      hosts:
        - localhost
